# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/proto/version/message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='temporal/proto/version/message.proto',
  package='version',
  syntax='proto3',
  serialized_options=b'\n\031io.temporal.proto.versionP\001Z%go.temporal.io/temporal-proto/version',
  serialized_pb=b'\n$temporal/proto/version/message.proto\x12\x07version\"9\n\x17SupportedClientVersions\x12\r\n\x05goSdk\x18\x01 \x01(\t\x12\x0f\n\x07javaSdk\x18\x02 \x01(\t\"9\n\x11WorkerVersionInfo\x12\x0c\n\x04impl\x18\x01 \x01(\t\x12\x16\n\x0e\x66\x65\x61tureVersion\x18\x02 \x01(\tBD\n\x19io.temporal.proto.versionP\x01Z%go.temporal.io/temporal-proto/versionb\x06proto3'
)




_SUPPORTEDCLIENTVERSIONS = _descriptor.Descriptor(
  name='SupportedClientVersions',
  full_name='version.SupportedClientVersions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='goSdk', full_name='version.SupportedClientVersions.goSdk', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='javaSdk', full_name='version.SupportedClientVersions.javaSdk', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=106,
)


_WORKERVERSIONINFO = _descriptor.Descriptor(
  name='WorkerVersionInfo',
  full_name='version.WorkerVersionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='impl', full_name='version.WorkerVersionInfo.impl', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='featureVersion', full_name='version.WorkerVersionInfo.featureVersion', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=165,
)

DESCRIPTOR.message_types_by_name['SupportedClientVersions'] = _SUPPORTEDCLIENTVERSIONS
DESCRIPTOR.message_types_by_name['WorkerVersionInfo'] = _WORKERVERSIONINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SupportedClientVersions = _reflection.GeneratedProtocolMessageType('SupportedClientVersions', (_message.Message,), {
  'DESCRIPTOR' : _SUPPORTEDCLIENTVERSIONS,
  '__module__' : 'temporal.proto.version.message_pb2'
  # @@protoc_insertion_point(class_scope:version.SupportedClientVersions)
  })
_sym_db.RegisterMessage(SupportedClientVersions)

WorkerVersionInfo = _reflection.GeneratedProtocolMessageType('WorkerVersionInfo', (_message.Message,), {
  'DESCRIPTOR' : _WORKERVERSIONINFO,
  '__module__' : 'temporal.proto.version.message_pb2'
  # @@protoc_insertion_point(class_scope:version.WorkerVersionInfo)
  })
_sym_db.RegisterMessage(WorkerVersionInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
