# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/proto/query/enum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='temporal/proto/query/enum.proto',
  package='query',
  syntax='proto3',
  serialized_options=b'\n\027io.temporal.proto.queryP\001Z#go.temporal.io/temporal-proto/query',
  serialized_pb=b'\n\x1ftemporal/proto/query/enum.proto\x12\x05query*+\n\x0fQueryResultType\x12\x0c\n\x08\x41nswered\x10\x00\x12\n\n\x06\x46\x61iled\x10\x01*F\n\x14QueryRejectCondition\x12\x08\n\x04None\x10\x00\x12\x0b\n\x07NotOpen\x10\x01\x12\x17\n\x13NotCompletedCleanly\x10\x02*1\n\x15QueryConsistencyLevel\x12\x0c\n\x08\x45ventual\x10\x00\x12\n\n\x06Strong\x10\x01\x42@\n\x17io.temporal.proto.queryP\x01Z#go.temporal.io/temporal-proto/queryb\x06proto3'
)

_QUERYRESULTTYPE = _descriptor.EnumDescriptor(
  name='QueryResultType',
  full_name='query.QueryResultType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Answered', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Failed', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=42,
  serialized_end=85,
)
_sym_db.RegisterEnumDescriptor(_QUERYRESULTTYPE)

QueryResultType = enum_type_wrapper.EnumTypeWrapper(_QUERYRESULTTYPE)
_QUERYREJECTCONDITION = _descriptor.EnumDescriptor(
  name='QueryRejectCondition',
  full_name='query.QueryRejectCondition',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='None', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NotOpen', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NotCompletedCleanly', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=87,
  serialized_end=157,
)
_sym_db.RegisterEnumDescriptor(_QUERYREJECTCONDITION)

QueryRejectCondition = enum_type_wrapper.EnumTypeWrapper(_QUERYREJECTCONDITION)
_QUERYCONSISTENCYLEVEL = _descriptor.EnumDescriptor(
  name='QueryConsistencyLevel',
  full_name='query.QueryConsistencyLevel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Eventual', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Strong', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=159,
  serialized_end=208,
)
_sym_db.RegisterEnumDescriptor(_QUERYCONSISTENCYLEVEL)

QueryConsistencyLevel = enum_type_wrapper.EnumTypeWrapper(_QUERYCONSISTENCYLEVEL)
Answered = 0
Failed = 1
globals()['None'] = 0
NotOpen = 1
NotCompletedCleanly = 2
Eventual = 0
Strong = 1


DESCRIPTOR.enum_types_by_name['QueryResultType'] = _QUERYRESULTTYPE
DESCRIPTOR.enum_types_by_name['QueryRejectCondition'] = _QUERYREJECTCONDITION
DESCRIPTOR.enum_types_by_name['QueryConsistencyLevel'] = _QUERYCONSISTENCYLEVEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
