# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/proto/namespace/enum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='temporal/proto/namespace/enum.proto',
  package='namespace',
  syntax='proto3',
  serialized_options=b'\n\033io.temporal.proto.namespaceP\001Z\'go.temporal.io/temporal-proto/namespace',
  serialized_pb=b'\n#temporal/proto/namespace/enum.proto\x12\tnamespace*>\n\x0fNamespaceStatus\x12\x0e\n\nRegistered\x10\x00\x12\x0e\n\nDeprecated\x10\x01\x12\x0b\n\x07\x44\x65leted\x10\x02*8\n\x0e\x41rchivalStatus\x12\x0b\n\x07\x44\x65\x66\x61ult\x10\x00\x12\x0c\n\x08\x44isabled\x10\x01\x12\x0b\n\x07\x45nabled\x10\x02\x42H\n\x1bio.temporal.proto.namespaceP\x01Z\'go.temporal.io/temporal-proto/namespaceb\x06proto3'
)

_NAMESPACESTATUS = _descriptor.EnumDescriptor(
  name='NamespaceStatus',
  full_name='namespace.NamespaceStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Registered', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Deprecated', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Deleted', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=50,
  serialized_end=112,
)
_sym_db.RegisterEnumDescriptor(_NAMESPACESTATUS)

NamespaceStatus = enum_type_wrapper.EnumTypeWrapper(_NAMESPACESTATUS)
_ARCHIVALSTATUS = _descriptor.EnumDescriptor(
  name='ArchivalStatus',
  full_name='namespace.ArchivalStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Default', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Disabled', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Enabled', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=114,
  serialized_end=170,
)
_sym_db.RegisterEnumDescriptor(_ARCHIVALSTATUS)

ArchivalStatus = enum_type_wrapper.EnumTypeWrapper(_ARCHIVALSTATUS)
Registered = 0
Deprecated = 1
Deleted = 2
Default = 0
Disabled = 1
Enabled = 2


DESCRIPTOR.enum_types_by_name['NamespaceStatus'] = _NAMESPACESTATUS
DESCRIPTOR.enum_types_by_name['ArchivalStatus'] = _ARCHIVALSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
