# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/proto/namespace/message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from temporal.proto.namespace import enum_pb2 as temporal_dot_proto_dot_namespace_dot_enum__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='temporal/proto/namespace/message.proto',
  package='namespace',
  syntax='proto3',
  serialized_options=b'\n\033io.temporal.proto.namespaceP\001Z\'go.temporal.io/temporal-proto/namespace',
  serialized_pb=b'\n&temporal/proto/namespace/message.proto\x12\tnamespace\x1a#temporal/proto/namespace/enum.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xdd\x01\n\rNamespaceInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12*\n\x06status\x18\x02 \x01(\x0e\x32\x1a.namespace.NamespaceStatus\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\nownerEmail\x18\x04 \x01(\t\x12\x30\n\x04\x64\x61ta\x18\x05 \x03(\x0b\x32\".namespace.NamespaceInfo.DataEntry\x12\n\n\x02id\x18\x06 \x01(\t\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xd7\x02\n\x16NamespaceConfiguration\x12.\n&workflowExecutionRetentionPeriodInDays\x18\x01 \x01(\x05\x12.\n\nemitMetric\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12+\n\x0b\x62\x61\x64\x42inaries\x18\x03 \x01(\x0b\x32\x16.namespace.BadBinaries\x12\x38\n\x15historyArchivalStatus\x18\x04 \x01(\x0e\x32\x19.namespace.ArchivalStatus\x12\x1a\n\x12historyArchivalURI\x18\x05 \x01(\t\x12;\n\x18visibilityArchivalStatus\x18\x06 \x01(\x0e\x32\x19.namespace.ArchivalStatus\x12\x1d\n\x15visibilityArchivalURI\x18\x07 \x01(\t\"\x90\x01\n\x0b\x42\x61\x64\x42inaries\x12\x36\n\x08\x62inaries\x18\x01 \x03(\x0b\x32$.namespace.BadBinaries.BinariesEntry\x1aI\n\rBinariesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.namespace.BadBinaryInfo:\x02\x38\x01\"J\n\rBadBinaryInfo\x12\x0e\n\x06reason\x18\x01 \x01(\t\x12\x10\n\x08operator\x18\x02 \x01(\t\x12\x17\n\x0f\x63reatedTimeNano\x18\x03 \x01(\x03\"\xa3\x01\n\x13UpdateNamespaceInfo\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x12\n\nownerEmail\x18\x02 \x01(\t\x12\x36\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32(.namespace.UpdateNamespaceInfo.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42H\n\x1bio.temporal.proto.namespaceP\x01Z\'go.temporal.io/temporal-proto/namespaceb\x06proto3'
  ,
  dependencies=[temporal_dot_proto_dot_namespace_dot_enum__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])




_NAMESPACEINFO_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='namespace.NamespaceInfo.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='namespace.NamespaceInfo.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='namespace.NamespaceInfo.DataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=344,
)

_NAMESPACEINFO = _descriptor.Descriptor(
  name='NamespaceInfo',
  full_name='namespace.NamespaceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='namespace.NamespaceInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='namespace.NamespaceInfo.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='namespace.NamespaceInfo.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ownerEmail', full_name='namespace.NamespaceInfo.ownerEmail', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='namespace.NamespaceInfo.data', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='namespace.NamespaceInfo.id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NAMESPACEINFO_DATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=344,
)


_NAMESPACECONFIGURATION = _descriptor.Descriptor(
  name='NamespaceConfiguration',
  full_name='namespace.NamespaceConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workflowExecutionRetentionPeriodInDays', full_name='namespace.NamespaceConfiguration.workflowExecutionRetentionPeriodInDays', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='emitMetric', full_name='namespace.NamespaceConfiguration.emitMetric', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='badBinaries', full_name='namespace.NamespaceConfiguration.badBinaries', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='historyArchivalStatus', full_name='namespace.NamespaceConfiguration.historyArchivalStatus', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='historyArchivalURI', full_name='namespace.NamespaceConfiguration.historyArchivalURI', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visibilityArchivalStatus', full_name='namespace.NamespaceConfiguration.visibilityArchivalStatus', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visibilityArchivalURI', full_name='namespace.NamespaceConfiguration.visibilityArchivalURI', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=690,
)


_BADBINARIES_BINARIESENTRY = _descriptor.Descriptor(
  name='BinariesEntry',
  full_name='namespace.BadBinaries.BinariesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='namespace.BadBinaries.BinariesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='namespace.BadBinaries.BinariesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=764,
  serialized_end=837,
)

_BADBINARIES = _descriptor.Descriptor(
  name='BadBinaries',
  full_name='namespace.BadBinaries',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='binaries', full_name='namespace.BadBinaries.binaries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BADBINARIES_BINARIESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=693,
  serialized_end=837,
)


_BADBINARYINFO = _descriptor.Descriptor(
  name='BadBinaryInfo',
  full_name='namespace.BadBinaryInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reason', full_name='namespace.BadBinaryInfo.reason', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operator', full_name='namespace.BadBinaryInfo.operator', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='createdTimeNano', full_name='namespace.BadBinaryInfo.createdTimeNano', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=839,
  serialized_end=913,
)


_UPDATENAMESPACEINFO_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='namespace.UpdateNamespaceInfo.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='namespace.UpdateNamespaceInfo.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='namespace.UpdateNamespaceInfo.DataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=344,
)

_UPDATENAMESPACEINFO = _descriptor.Descriptor(
  name='UpdateNamespaceInfo',
  full_name='namespace.UpdateNamespaceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='namespace.UpdateNamespaceInfo.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ownerEmail', full_name='namespace.UpdateNamespaceInfo.ownerEmail', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='namespace.UpdateNamespaceInfo.data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_UPDATENAMESPACEINFO_DATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=916,
  serialized_end=1079,
)

_NAMESPACEINFO_DATAENTRY.containing_type = _NAMESPACEINFO
_NAMESPACEINFO.fields_by_name['status'].enum_type = temporal_dot_proto_dot_namespace_dot_enum__pb2._NAMESPACESTATUS
_NAMESPACEINFO.fields_by_name['data'].message_type = _NAMESPACEINFO_DATAENTRY
_NAMESPACECONFIGURATION.fields_by_name['emitMetric'].message_type = google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE
_NAMESPACECONFIGURATION.fields_by_name['badBinaries'].message_type = _BADBINARIES
_NAMESPACECONFIGURATION.fields_by_name['historyArchivalStatus'].enum_type = temporal_dot_proto_dot_namespace_dot_enum__pb2._ARCHIVALSTATUS
_NAMESPACECONFIGURATION.fields_by_name['visibilityArchivalStatus'].enum_type = temporal_dot_proto_dot_namespace_dot_enum__pb2._ARCHIVALSTATUS
_BADBINARIES_BINARIESENTRY.fields_by_name['value'].message_type = _BADBINARYINFO
_BADBINARIES_BINARIESENTRY.containing_type = _BADBINARIES
_BADBINARIES.fields_by_name['binaries'].message_type = _BADBINARIES_BINARIESENTRY
_UPDATENAMESPACEINFO_DATAENTRY.containing_type = _UPDATENAMESPACEINFO
_UPDATENAMESPACEINFO.fields_by_name['data'].message_type = _UPDATENAMESPACEINFO_DATAENTRY
DESCRIPTOR.message_types_by_name['NamespaceInfo'] = _NAMESPACEINFO
DESCRIPTOR.message_types_by_name['NamespaceConfiguration'] = _NAMESPACECONFIGURATION
DESCRIPTOR.message_types_by_name['BadBinaries'] = _BADBINARIES
DESCRIPTOR.message_types_by_name['BadBinaryInfo'] = _BADBINARYINFO
DESCRIPTOR.message_types_by_name['UpdateNamespaceInfo'] = _UPDATENAMESPACEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NamespaceInfo = _reflection.GeneratedProtocolMessageType('NamespaceInfo', (_message.Message,), {

  'DataEntry' : _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), {
    'DESCRIPTOR' : _NAMESPACEINFO_DATAENTRY,
    '__module__' : 'temporal.proto.namespace.message_pb2'
    # @@protoc_insertion_point(class_scope:namespace.NamespaceInfo.DataEntry)
    })
  ,
  'DESCRIPTOR' : _NAMESPACEINFO,
  '__module__' : 'temporal.proto.namespace.message_pb2'
  # @@protoc_insertion_point(class_scope:namespace.NamespaceInfo)
  })
_sym_db.RegisterMessage(NamespaceInfo)
_sym_db.RegisterMessage(NamespaceInfo.DataEntry)

NamespaceConfiguration = _reflection.GeneratedProtocolMessageType('NamespaceConfiguration', (_message.Message,), {
  'DESCRIPTOR' : _NAMESPACECONFIGURATION,
  '__module__' : 'temporal.proto.namespace.message_pb2'
  # @@protoc_insertion_point(class_scope:namespace.NamespaceConfiguration)
  })
_sym_db.RegisterMessage(NamespaceConfiguration)

BadBinaries = _reflection.GeneratedProtocolMessageType('BadBinaries', (_message.Message,), {

  'BinariesEntry' : _reflection.GeneratedProtocolMessageType('BinariesEntry', (_message.Message,), {
    'DESCRIPTOR' : _BADBINARIES_BINARIESENTRY,
    '__module__' : 'temporal.proto.namespace.message_pb2'
    # @@protoc_insertion_point(class_scope:namespace.BadBinaries.BinariesEntry)
    })
  ,
  'DESCRIPTOR' : _BADBINARIES,
  '__module__' : 'temporal.proto.namespace.message_pb2'
  # @@protoc_insertion_point(class_scope:namespace.BadBinaries)
  })
_sym_db.RegisterMessage(BadBinaries)
_sym_db.RegisterMessage(BadBinaries.BinariesEntry)

BadBinaryInfo = _reflection.GeneratedProtocolMessageType('BadBinaryInfo', (_message.Message,), {
  'DESCRIPTOR' : _BADBINARYINFO,
  '__module__' : 'temporal.proto.namespace.message_pb2'
  # @@protoc_insertion_point(class_scope:namespace.BadBinaryInfo)
  })
_sym_db.RegisterMessage(BadBinaryInfo)

UpdateNamespaceInfo = _reflection.GeneratedProtocolMessageType('UpdateNamespaceInfo', (_message.Message,), {

  'DataEntry' : _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), {
    'DESCRIPTOR' : _UPDATENAMESPACEINFO_DATAENTRY,
    '__module__' : 'temporal.proto.namespace.message_pb2'
    # @@protoc_insertion_point(class_scope:namespace.UpdateNamespaceInfo.DataEntry)
    })
  ,
  'DESCRIPTOR' : _UPDATENAMESPACEINFO,
  '__module__' : 'temporal.proto.namespace.message_pb2'
  # @@protoc_insertion_point(class_scope:namespace.UpdateNamespaceInfo)
  })
_sym_db.RegisterMessage(UpdateNamespaceInfo)
_sym_db.RegisterMessage(UpdateNamespaceInfo.DataEntry)


DESCRIPTOR._options = None
_NAMESPACEINFO_DATAENTRY._options = None
_BADBINARIES_BINARIESENTRY._options = None
_UPDATENAMESPACEINFO_DATAENTRY._options = None
# @@protoc_insertion_point(module_scope)
