# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/proto/common/enum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='temporal/proto/common/enum.proto',
  package='common',
  syntax='proto3',
  serialized_options=b'\n\030io.temporal.proto.commonP\001Z$go.temporal.io/temporal-proto/common',
  serialized_pb=b'\n temporal/proto/common/enum.proto\x12\x06\x63ommon*$\n\x0c\x45ncodingType\x12\n\n\x06Proto3\x10\x00\x12\x08\n\x04JSON\x10\x01*^\n\x15WorkflowIdReusePolicy\x12\x12\n\x0e\x41llowDuplicate\x10\x00\x12\x1c\n\x18\x41llowDuplicateFailedOnly\x10\x01\x12\x13\n\x0fRejectDuplicate\x10\x02*B\n\x11ParentClosePolicy\x12\x0b\n\x07\x41\x62\x61ndon\x10\x00\x12\x11\n\rRequestCancel\x10\x01\x12\r\n\tTerminate\x10\x02*X\n\x10IndexedValueType\x12\n\n\x06String\x10\x00\x12\x0b\n\x07Keyword\x10\x01\x12\x07\n\x03Int\x10\x02\x12\n\n\x06\x44ouble\x10\x03\x12\x08\n\x04\x42ool\x10\x04\x12\x0c\n\x08\x44\x61tetime\x10\x05*B\n\x16\x43ontinueAsNewInitiator\x12\x0b\n\x07\x44\x65\x63ider\x10\x00\x12\t\n\x05Retry\x10\x01\x12\x10\n\x0c\x43ronSchedule\x10\x02\x42\x42\n\x18io.temporal.proto.commonP\x01Z$go.temporal.io/temporal-proto/commonb\x06proto3'
)

_ENCODINGTYPE = _descriptor.EnumDescriptor(
  name='EncodingType',
  full_name='common.EncodingType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Proto3', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JSON', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=44,
  serialized_end=80,
)
_sym_db.RegisterEnumDescriptor(_ENCODINGTYPE)

EncodingType = enum_type_wrapper.EnumTypeWrapper(_ENCODINGTYPE)
_WORKFLOWIDREUSEPOLICY = _descriptor.EnumDescriptor(
  name='WorkflowIdReusePolicy',
  full_name='common.WorkflowIdReusePolicy',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AllowDuplicate', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AllowDuplicateFailedOnly', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RejectDuplicate', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=82,
  serialized_end=176,
)
_sym_db.RegisterEnumDescriptor(_WORKFLOWIDREUSEPOLICY)

WorkflowIdReusePolicy = enum_type_wrapper.EnumTypeWrapper(_WORKFLOWIDREUSEPOLICY)
_PARENTCLOSEPOLICY = _descriptor.EnumDescriptor(
  name='ParentClosePolicy',
  full_name='common.ParentClosePolicy',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Abandon', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RequestCancel', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Terminate', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=178,
  serialized_end=244,
)
_sym_db.RegisterEnumDescriptor(_PARENTCLOSEPOLICY)

ParentClosePolicy = enum_type_wrapper.EnumTypeWrapper(_PARENTCLOSEPOLICY)
_INDEXEDVALUETYPE = _descriptor.EnumDescriptor(
  name='IndexedValueType',
  full_name='common.IndexedValueType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='String', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Keyword', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Int', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Double', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Bool', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Datetime', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=246,
  serialized_end=334,
)
_sym_db.RegisterEnumDescriptor(_INDEXEDVALUETYPE)

IndexedValueType = enum_type_wrapper.EnumTypeWrapper(_INDEXEDVALUETYPE)
_CONTINUEASNEWINITIATOR = _descriptor.EnumDescriptor(
  name='ContinueAsNewInitiator',
  full_name='common.ContinueAsNewInitiator',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Decider', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Retry', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CronSchedule', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=336,
  serialized_end=402,
)
_sym_db.RegisterEnumDescriptor(_CONTINUEASNEWINITIATOR)

ContinueAsNewInitiator = enum_type_wrapper.EnumTypeWrapper(_CONTINUEASNEWINITIATOR)
Proto3 = 0
JSON = 1
AllowDuplicate = 0
AllowDuplicateFailedOnly = 1
RejectDuplicate = 2
Abandon = 0
RequestCancel = 1
Terminate = 2
String = 0
Keyword = 1
Int = 2
Double = 3
Bool = 4
Datetime = 5
Decider = 0
Retry = 1
CronSchedule = 2


DESCRIPTOR.enum_types_by_name['EncodingType'] = _ENCODINGTYPE
DESCRIPTOR.enum_types_by_name['WorkflowIdReusePolicy'] = _WORKFLOWIDREUSEPOLICY
DESCRIPTOR.enum_types_by_name['ParentClosePolicy'] = _PARENTCLOSEPOLICY
DESCRIPTOR.enum_types_by_name['IndexedValueType'] = _INDEXEDVALUETYPE
DESCRIPTOR.enum_types_by_name['ContinueAsNewInitiator'] = _CONTINUEASNEWINITIATOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
