# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/proto/common/message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from temporal.proto.common import enum_pb2 as temporal_dot_proto_dot_common_dot_enum__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='temporal/proto/common/message.proto',
  package='common',
  syntax='proto3',
  serialized_options=b'\n\030io.temporal.proto.commonP\001Z$go.temporal.io/temporal-proto/common',
  serialized_pb=b'\n#temporal/proto/common/message.proto\x12\x06\x63ommon\x1a temporal/proto/common/enum.proto\"D\n\x08\x44\x61taBlob\x12*\n\x0c\x65ncodingType\x18\x01 \x01(\x0e\x32\x14.common.EncodingType\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"-\n\x08Payloads\x12!\n\x08payloads\x18\x01 \x03(\x0b\x32\x0f.common.Payload\"y\n\x07Payload\x12/\n\x08metadata\x18\x01 \x03(\x0b\x32\x1d.common.Payload.MetadataEntry\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"\x1c\n\x0cWorkflowType\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\x0c\x41\x63tivityType\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x9e\x01\n\x10SearchAttributes\x12\x42\n\rindexedFields\x18\x01 \x03(\x0b\x32+.common.SearchAttributes.IndexedFieldsEntry\x1a\x46\n\x12IndexedFieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.common.Payloads:\x02\x38\x01\"q\n\x04Memo\x12(\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x18.common.Memo.FieldsEntry\x1a?\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.common.Payloads:\x02\x38\x01\"u\n\x06Header\x12*\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x1a.common.Header.FieldsEntry\x1a?\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.common.Payloads:\x02\x38\x01\"\xa8\x01\n\x0bRetryPolicy\x12 \n\x18initialIntervalInSeconds\x18\x01 \x01(\x05\x12\x1a\n\x12\x62\x61\x63koffCoefficient\x18\x02 \x01(\x01\x12 \n\x18maximumIntervalInSeconds\x18\x03 \x01(\x05\x12\x17\n\x0fmaximumAttempts\x18\x04 \x01(\x05\x12 \n\x18nonRetriableErrorReasons\x18\x05 \x03(\tBB\n\x18io.temporal.proto.commonP\x01Z$go.temporal.io/temporal-proto/commonb\x06proto3'
  ,
  dependencies=[temporal_dot_proto_dot_common_dot_enum__pb2.DESCRIPTOR,])




_DATABLOB = _descriptor.Descriptor(
  name='DataBlob',
  full_name='common.DataBlob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encodingType', full_name='common.DataBlob.encodingType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='common.DataBlob.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=149,
)


_PAYLOADS = _descriptor.Descriptor(
  name='Payloads',
  full_name='common.Payloads',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payloads', full_name='common.Payloads.payloads', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=196,
)


_PAYLOAD_METADATAENTRY = _descriptor.Descriptor(
  name='MetadataEntry',
  full_name='common.Payload.MetadataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='common.Payload.MetadataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='common.Payload.MetadataEntry.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=319,
)

_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='common.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='common.Payload.metadata', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='common.Payload.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PAYLOAD_METADATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=319,
)


_WORKFLOWTYPE = _descriptor.Descriptor(
  name='WorkflowType',
  full_name='common.WorkflowType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='common.WorkflowType.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=349,
)


_ACTIVITYTYPE = _descriptor.Descriptor(
  name='ActivityType',
  full_name='common.ActivityType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='common.ActivityType.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=379,
)


_SEARCHATTRIBUTES_INDEXEDFIELDSENTRY = _descriptor.Descriptor(
  name='IndexedFieldsEntry',
  full_name='common.SearchAttributes.IndexedFieldsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='common.SearchAttributes.IndexedFieldsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='common.SearchAttributes.IndexedFieldsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=470,
  serialized_end=540,
)

_SEARCHATTRIBUTES = _descriptor.Descriptor(
  name='SearchAttributes',
  full_name='common.SearchAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='indexedFields', full_name='common.SearchAttributes.indexedFields', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SEARCHATTRIBUTES_INDEXEDFIELDSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=382,
  serialized_end=540,
)


_MEMO_FIELDSENTRY = _descriptor.Descriptor(
  name='FieldsEntry',
  full_name='common.Memo.FieldsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='common.Memo.FieldsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='common.Memo.FieldsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=592,
  serialized_end=655,
)

_MEMO = _descriptor.Descriptor(
  name='Memo',
  full_name='common.Memo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fields', full_name='common.Memo.fields', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MEMO_FIELDSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=542,
  serialized_end=655,
)


_HEADER_FIELDSENTRY = _descriptor.Descriptor(
  name='FieldsEntry',
  full_name='common.Header.FieldsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='common.Header.FieldsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='common.Header.FieldsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=592,
  serialized_end=655,
)

_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='common.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fields', full_name='common.Header.fields', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_HEADER_FIELDSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=657,
  serialized_end=774,
)


_RETRYPOLICY = _descriptor.Descriptor(
  name='RetryPolicy',
  full_name='common.RetryPolicy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='initialIntervalInSeconds', full_name='common.RetryPolicy.initialIntervalInSeconds', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='backoffCoefficient', full_name='common.RetryPolicy.backoffCoefficient', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maximumIntervalInSeconds', full_name='common.RetryPolicy.maximumIntervalInSeconds', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maximumAttempts', full_name='common.RetryPolicy.maximumAttempts', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nonRetriableErrorReasons', full_name='common.RetryPolicy.nonRetriableErrorReasons', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=777,
  serialized_end=945,
)

_DATABLOB.fields_by_name['encodingType'].enum_type = temporal_dot_proto_dot_common_dot_enum__pb2._ENCODINGTYPE
_PAYLOADS.fields_by_name['payloads'].message_type = _PAYLOAD
_PAYLOAD_METADATAENTRY.containing_type = _PAYLOAD
_PAYLOAD.fields_by_name['metadata'].message_type = _PAYLOAD_METADATAENTRY
_SEARCHATTRIBUTES_INDEXEDFIELDSENTRY.fields_by_name['value'].message_type = _PAYLOADS
_SEARCHATTRIBUTES_INDEXEDFIELDSENTRY.containing_type = _SEARCHATTRIBUTES
_SEARCHATTRIBUTES.fields_by_name['indexedFields'].message_type = _SEARCHATTRIBUTES_INDEXEDFIELDSENTRY
_MEMO_FIELDSENTRY.fields_by_name['value'].message_type = _PAYLOADS
_MEMO_FIELDSENTRY.containing_type = _MEMO
_MEMO.fields_by_name['fields'].message_type = _MEMO_FIELDSENTRY
_HEADER_FIELDSENTRY.fields_by_name['value'].message_type = _PAYLOADS
_HEADER_FIELDSENTRY.containing_type = _HEADER
_HEADER.fields_by_name['fields'].message_type = _HEADER_FIELDSENTRY
DESCRIPTOR.message_types_by_name['DataBlob'] = _DATABLOB
DESCRIPTOR.message_types_by_name['Payloads'] = _PAYLOADS
DESCRIPTOR.message_types_by_name['Payload'] = _PAYLOAD
DESCRIPTOR.message_types_by_name['WorkflowType'] = _WORKFLOWTYPE
DESCRIPTOR.message_types_by_name['ActivityType'] = _ACTIVITYTYPE
DESCRIPTOR.message_types_by_name['SearchAttributes'] = _SEARCHATTRIBUTES
DESCRIPTOR.message_types_by_name['Memo'] = _MEMO
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['RetryPolicy'] = _RETRYPOLICY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataBlob = _reflection.GeneratedProtocolMessageType('DataBlob', (_message.Message,), {
  'DESCRIPTOR' : _DATABLOB,
  '__module__' : 'temporal.proto.common.message_pb2'
  # @@protoc_insertion_point(class_scope:common.DataBlob)
  })
_sym_db.RegisterMessage(DataBlob)

Payloads = _reflection.GeneratedProtocolMessageType('Payloads', (_message.Message,), {
  'DESCRIPTOR' : _PAYLOADS,
  '__module__' : 'temporal.proto.common.message_pb2'
  # @@protoc_insertion_point(class_scope:common.Payloads)
  })
_sym_db.RegisterMessage(Payloads)

Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), {

  'MetadataEntry' : _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _PAYLOAD_METADATAENTRY,
    '__module__' : 'temporal.proto.common.message_pb2'
    # @@protoc_insertion_point(class_scope:common.Payload.MetadataEntry)
    })
  ,
  'DESCRIPTOR' : _PAYLOAD,
  '__module__' : 'temporal.proto.common.message_pb2'
  # @@protoc_insertion_point(class_scope:common.Payload)
  })
_sym_db.RegisterMessage(Payload)
_sym_db.RegisterMessage(Payload.MetadataEntry)

WorkflowType = _reflection.GeneratedProtocolMessageType('WorkflowType', (_message.Message,), {
  'DESCRIPTOR' : _WORKFLOWTYPE,
  '__module__' : 'temporal.proto.common.message_pb2'
  # @@protoc_insertion_point(class_scope:common.WorkflowType)
  })
_sym_db.RegisterMessage(WorkflowType)

ActivityType = _reflection.GeneratedProtocolMessageType('ActivityType', (_message.Message,), {
  'DESCRIPTOR' : _ACTIVITYTYPE,
  '__module__' : 'temporal.proto.common.message_pb2'
  # @@protoc_insertion_point(class_scope:common.ActivityType)
  })
_sym_db.RegisterMessage(ActivityType)

SearchAttributes = _reflection.GeneratedProtocolMessageType('SearchAttributes', (_message.Message,), {

  'IndexedFieldsEntry' : _reflection.GeneratedProtocolMessageType('IndexedFieldsEntry', (_message.Message,), {
    'DESCRIPTOR' : _SEARCHATTRIBUTES_INDEXEDFIELDSENTRY,
    '__module__' : 'temporal.proto.common.message_pb2'
    # @@protoc_insertion_point(class_scope:common.SearchAttributes.IndexedFieldsEntry)
    })
  ,
  'DESCRIPTOR' : _SEARCHATTRIBUTES,
  '__module__' : 'temporal.proto.common.message_pb2'
  # @@protoc_insertion_point(class_scope:common.SearchAttributes)
  })
_sym_db.RegisterMessage(SearchAttributes)
_sym_db.RegisterMessage(SearchAttributes.IndexedFieldsEntry)

Memo = _reflection.GeneratedProtocolMessageType('Memo', (_message.Message,), {

  'FieldsEntry' : _reflection.GeneratedProtocolMessageType('FieldsEntry', (_message.Message,), {
    'DESCRIPTOR' : _MEMO_FIELDSENTRY,
    '__module__' : 'temporal.proto.common.message_pb2'
    # @@protoc_insertion_point(class_scope:common.Memo.FieldsEntry)
    })
  ,
  'DESCRIPTOR' : _MEMO,
  '__module__' : 'temporal.proto.common.message_pb2'
  # @@protoc_insertion_point(class_scope:common.Memo)
  })
_sym_db.RegisterMessage(Memo)
_sym_db.RegisterMessage(Memo.FieldsEntry)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), {

  'FieldsEntry' : _reflection.GeneratedProtocolMessageType('FieldsEntry', (_message.Message,), {
    'DESCRIPTOR' : _HEADER_FIELDSENTRY,
    '__module__' : 'temporal.proto.common.message_pb2'
    # @@protoc_insertion_point(class_scope:common.Header.FieldsEntry)
    })
  ,
  'DESCRIPTOR' : _HEADER,
  '__module__' : 'temporal.proto.common.message_pb2'
  # @@protoc_insertion_point(class_scope:common.Header)
  })
_sym_db.RegisterMessage(Header)
_sym_db.RegisterMessage(Header.FieldsEntry)

RetryPolicy = _reflection.GeneratedProtocolMessageType('RetryPolicy', (_message.Message,), {
  'DESCRIPTOR' : _RETRYPOLICY,
  '__module__' : 'temporal.proto.common.message_pb2'
  # @@protoc_insertion_point(class_scope:common.RetryPolicy)
  })
_sym_db.RegisterMessage(RetryPolicy)


DESCRIPTOR._options = None
_PAYLOAD_METADATAENTRY._options = None
_SEARCHATTRIBUTES_INDEXEDFIELDSENTRY._options = None
_MEMO_FIELDSENTRY._options = None
_HEADER_FIELDSENTRY._options = None
# @@protoc_insertion_point(module_scope)
