# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/proto/tasklist/enum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='temporal/proto/tasklist/enum.proto',
  package='tasklist',
  syntax='proto3',
  serialized_options=b'\n\032io.temporal.proto.tasklistP\001Z&go.temporal.io/temporal-proto/tasklist',
  serialized_pb=b'\n\"temporal/proto/tasklist/enum.proto\x12\x08tasklist*&\n\x0cTaskListKind\x12\n\n\x06Normal\x10\x00\x12\n\n\x06Sticky\x10\x01**\n\x0cTaskListType\x12\x0c\n\x08\x44\x65\x63ision\x10\x00\x12\x0c\n\x08\x41\x63tivity\x10\x01\x42\x46\n\x1aio.temporal.proto.tasklistP\x01Z&go.temporal.io/temporal-proto/tasklistb\x06proto3'
)

_TASKLISTKIND = _descriptor.EnumDescriptor(
  name='TaskListKind',
  full_name='tasklist.TaskListKind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Normal', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Sticky', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=48,
  serialized_end=86,
)
_sym_db.RegisterEnumDescriptor(_TASKLISTKIND)

TaskListKind = enum_type_wrapper.EnumTypeWrapper(_TASKLISTKIND)
_TASKLISTTYPE = _descriptor.EnumDescriptor(
  name='TaskListType',
  full_name='tasklist.TaskListType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Decision', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Activity', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=88,
  serialized_end=130,
)
_sym_db.RegisterEnumDescriptor(_TASKLISTTYPE)

TaskListType = enum_type_wrapper.EnumTypeWrapper(_TASKLISTTYPE)
Normal = 0
Sticky = 1
Decision = 0
Activity = 1


DESCRIPTOR.enum_types_by_name['TaskListKind'] = _TASKLISTKIND
DESCRIPTOR.enum_types_by_name['TaskListType'] = _TASKLISTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
