# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/proto/tasklist/message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from temporal.proto.tasklist import enum_pb2 as temporal_dot_proto_dot_tasklist_dot_enum__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='temporal/proto/tasklist/message.proto',
  package='tasklist',
  syntax='proto3',
  serialized_options=b'\n\032io.temporal.proto.tasklistP\001Z&go.temporal.io/temporal-proto/tasklist',
  serialized_pb=b'\n%temporal/proto/tasklist/message.proto\x12\x08tasklist\x1a\"temporal/proto/tasklist/enum.proto\x1a\x1egoogle/protobuf/wrappers.proto\">\n\x08TaskList\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\x04kind\x18\x02 \x01(\x0e\x32\x16.tasklist.TaskListKind\"K\n\x10TaskListMetadata\x12\x37\n\x11maxTasksPerSecond\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\"\x92\x01\n\x0eTaskListStatus\x12\x18\n\x10\x62\x61\x63klogCountHint\x18\x01 \x01(\x03\x12\x11\n\treadLevel\x18\x02 \x01(\x03\x12\x10\n\x08\x61\x63kLevel\x18\x03 \x01(\x03\x12\x15\n\rratePerSecond\x18\x04 \x01(\x01\x12*\n\x0btaskIdBlock\x18\x05 \x01(\x0b\x32\x15.tasklist.TaskIdBlock\"-\n\x0bTaskIdBlock\x12\x0f\n\x07startId\x18\x01 \x01(\x03\x12\r\n\x05\x65ndId\x18\x02 \x01(\x03\"?\n\x19TaskListPartitionMetadata\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x15\n\rownerHostName\x18\x02 \x01(\t\"M\n\nPollerInfo\x12\x16\n\x0elastAccessTime\x18\x01 \x01(\x03\x12\x10\n\x08identity\x18\x02 \x01(\t\x12\x15\n\rratePerSecond\x18\x03 \x01(\x01\x42\x46\n\x1aio.temporal.proto.tasklistP\x01Z&go.temporal.io/temporal-proto/tasklistb\x06proto3'
  ,
  dependencies=[temporal_dot_proto_dot_tasklist_dot_enum__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])




_TASKLIST = _descriptor.Descriptor(
  name='TaskList',
  full_name='tasklist.TaskList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tasklist.TaskList.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kind', full_name='tasklist.TaskList.kind', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=181,
)


_TASKLISTMETADATA = _descriptor.Descriptor(
  name='TaskListMetadata',
  full_name='tasklist.TaskListMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='maxTasksPerSecond', full_name='tasklist.TaskListMetadata.maxTasksPerSecond', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=258,
)


_TASKLISTSTATUS = _descriptor.Descriptor(
  name='TaskListStatus',
  full_name='tasklist.TaskListStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='backlogCountHint', full_name='tasklist.TaskListStatus.backlogCountHint', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='readLevel', full_name='tasklist.TaskListStatus.readLevel', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ackLevel', full_name='tasklist.TaskListStatus.ackLevel', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ratePerSecond', full_name='tasklist.TaskListStatus.ratePerSecond', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='taskIdBlock', full_name='tasklist.TaskListStatus.taskIdBlock', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=407,
)


_TASKIDBLOCK = _descriptor.Descriptor(
  name='TaskIdBlock',
  full_name='tasklist.TaskIdBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='startId', full_name='tasklist.TaskIdBlock.startId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='endId', full_name='tasklist.TaskIdBlock.endId', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=409,
  serialized_end=454,
)


_TASKLISTPARTITIONMETADATA = _descriptor.Descriptor(
  name='TaskListPartitionMetadata',
  full_name='tasklist.TaskListPartitionMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='tasklist.TaskListPartitionMetadata.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ownerHostName', full_name='tasklist.TaskListPartitionMetadata.ownerHostName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=456,
  serialized_end=519,
)


_POLLERINFO = _descriptor.Descriptor(
  name='PollerInfo',
  full_name='tasklist.PollerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lastAccessTime', full_name='tasklist.PollerInfo.lastAccessTime', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='identity', full_name='tasklist.PollerInfo.identity', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ratePerSecond', full_name='tasklist.PollerInfo.ratePerSecond', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=521,
  serialized_end=598,
)

_TASKLIST.fields_by_name['kind'].enum_type = temporal_dot_proto_dot_tasklist_dot_enum__pb2._TASKLISTKIND
_TASKLISTMETADATA.fields_by_name['maxTasksPerSecond'].message_type = google_dot_protobuf_dot_wrappers__pb2._DOUBLEVALUE
_TASKLISTSTATUS.fields_by_name['taskIdBlock'].message_type = _TASKIDBLOCK
DESCRIPTOR.message_types_by_name['TaskList'] = _TASKLIST
DESCRIPTOR.message_types_by_name['TaskListMetadata'] = _TASKLISTMETADATA
DESCRIPTOR.message_types_by_name['TaskListStatus'] = _TASKLISTSTATUS
DESCRIPTOR.message_types_by_name['TaskIdBlock'] = _TASKIDBLOCK
DESCRIPTOR.message_types_by_name['TaskListPartitionMetadata'] = _TASKLISTPARTITIONMETADATA
DESCRIPTOR.message_types_by_name['PollerInfo'] = _POLLERINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskList = _reflection.GeneratedProtocolMessageType('TaskList', (_message.Message,), {
  'DESCRIPTOR' : _TASKLIST,
  '__module__' : 'temporal.proto.tasklist.message_pb2'
  # @@protoc_insertion_point(class_scope:tasklist.TaskList)
  })
_sym_db.RegisterMessage(TaskList)

TaskListMetadata = _reflection.GeneratedProtocolMessageType('TaskListMetadata', (_message.Message,), {
  'DESCRIPTOR' : _TASKLISTMETADATA,
  '__module__' : 'temporal.proto.tasklist.message_pb2'
  # @@protoc_insertion_point(class_scope:tasklist.TaskListMetadata)
  })
_sym_db.RegisterMessage(TaskListMetadata)

TaskListStatus = _reflection.GeneratedProtocolMessageType('TaskListStatus', (_message.Message,), {
  'DESCRIPTOR' : _TASKLISTSTATUS,
  '__module__' : 'temporal.proto.tasklist.message_pb2'
  # @@protoc_insertion_point(class_scope:tasklist.TaskListStatus)
  })
_sym_db.RegisterMessage(TaskListStatus)

TaskIdBlock = _reflection.GeneratedProtocolMessageType('TaskIdBlock', (_message.Message,), {
  'DESCRIPTOR' : _TASKIDBLOCK,
  '__module__' : 'temporal.proto.tasklist.message_pb2'
  # @@protoc_insertion_point(class_scope:tasklist.TaskIdBlock)
  })
_sym_db.RegisterMessage(TaskIdBlock)

TaskListPartitionMetadata = _reflection.GeneratedProtocolMessageType('TaskListPartitionMetadata', (_message.Message,), {
  'DESCRIPTOR' : _TASKLISTPARTITIONMETADATA,
  '__module__' : 'temporal.proto.tasklist.message_pb2'
  # @@protoc_insertion_point(class_scope:tasklist.TaskListPartitionMetadata)
  })
_sym_db.RegisterMessage(TaskListPartitionMetadata)

PollerInfo = _reflection.GeneratedProtocolMessageType('PollerInfo', (_message.Message,), {
  'DESCRIPTOR' : _POLLERINFO,
  '__module__' : 'temporal.proto.tasklist.message_pb2'
  # @@protoc_insertion_point(class_scope:tasklist.PollerInfo)
  })
_sym_db.RegisterMessage(PollerInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
